args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2L) stop("Usage: Rscript print_hpc_commands.R <MIMIC_ROOT> <OUTPUT_DIR>")
repo <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
cat(sprintf('export MIMIC_ROOT=%s\n', shQuote(normalizePath(args[[1]], winslash = "/", mustWork = FALSE))))
cat(sprintf('export SEPSIS_HMM_CODE_DIR=%s\n', shQuote(file.path(repo, "R"))))
cat(sprintf('export SEPSIS_HMM_RESOURCE_DIR=%s\n', shQuote(file.path(repo, "resources"))))
cat(sprintf('export SEPSIS_HMM_OUTPUT_DIR=%s\n', shQuote(normalizePath(args[[2]], winslash = "/", mustWork = FALSE))))
cat('export MIMIC_K_MIN=5\nexport MIMIC_K_MAX=65\n')
cat('\n')
for (i in 1:20) cat(sprintf('Rscript "$SEPSIS_HMM_CODE_DIR/08_prepare_model_selection_split.R" %d\n', i))
cat('\n')
for (i in 1:20) for (k in 5:65) cat(sprintf('Rscript "$SEPSIS_HMM_CODE_DIR/09_fit_model_selection_candidate.R" %d %d\n', k, i))
cat('\nRscript "$SEPSIS_HMM_CODE_DIR/10_select_state_dimension.R" 20\n')
cat('Rscript "$SEPSIS_HMM_CODE_DIR/11_prepare_full_cohort.R"\n')
cat('\n')
for (s in 1:20) cat(sprintf('Rscript "$SEPSIS_HMM_CODE_DIR/12_fit_full_cohort_start.R" 60 %d\n', s))
cat('Rscript "$SEPSIS_HMM_CODE_DIR/13_select_final_model.R" 60 20\n')
cat('Rscript "$SEPSIS_HMM_CODE_DIR/19_run_annotation.R"\n')
cat('Rscript "$SEPSIS_HMM_CODE_DIR/34_run_downstream_analyses.R"\n')
