
source(file.path(Sys.getenv("SEPSIS_HMM_CODE_DIR", unset = file.path(getwd(), "R")), "00_setup.R"))
source(code_path("00_packages.R"))
source(code_path("14_load_final_model.R"))
source(code_path("20_state_outcome_summary.R"))
source(code_path("21_state_mortality_timeseries.R"))
source(code_path("22_day21_destinations.R"))
source(code_path("23_state_dominance_qc.R"))
source(code_path("24_filtering_sensitivity.R"))
source(code_path("25_filtering_key_estimates.R"))
source(code_path("26_incremental_value_admission_sofa.R"))
source(code_path("27_incremental_value_diagnostics.R"))
source(code_path("28_patient_day_sofa_organsupport.R"))
source(code_path("29_incremental_value_current_sofa.R"))
source(code_path("30_patient_level_out_of_fold_validation.R"))
source(code_path("31_organsupport_descriptive_summary.R"))
source(code_path("32_next_day_organ_burden.R"))
source(code_path("33_state_transition_analysis.R"))
